name: ebook_toolkit
description: Dart ebook toolkit to parse epub files and more. Epubx package fork.
version: 0.0.1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  archive: ^4.0.9

  collection: ^1.19.1

  equatable: ^2.0.8

  flutter:
    sdk: flutter

  image: ^4.8.0

  path: ^1.9.1

  plugin_platform_interface: ^2.1.8

  quiver: ^3.2.2

  xml: ^6.6.1

dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  test: ^1.25.15

  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wakek.ebook_toolkit
        pluginClass: EbookToolkitPlugin
